# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16.4
    container_name: MichelleDb
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: parking-control-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco-123
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:    
